# Generated by Django 5.2.9 on 2025-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True, verbose_name='Buyurtma ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narx')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ism Familya')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('region', models.CharField(blank=True, max_length=120, null=True, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, max_length=120, null=True, verbose_name='Tuman')),
                ('payment_method', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta orqali'), ('click', 'Click / Payme'), ('bank', 'Bank orqali')], max_length=20, verbose_name="To'lov usuli")),
                ('comments', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izohlar")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', "Yo'lda"), ('completed', 'Yetkazilgan'), ('canceled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='store.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
