# Generated by Django 5.2.9 on 2025-12-06 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram username')),
                ('region', models.CharField(choices=[('tashkent', 'Toshkent'), ('samarkand', 'Samarqand'), ('bukhara', 'Buxoro'), ('andijan', 'Andijon'), ('fergana', "Farg'ona"), ('namangan', 'Namangan'), ('kashkadarya', 'Qashqadaryo'), ('surkhandarya', 'Surxondaryo'), ('jizzakh', 'Jizzax'), ('syrdarya', 'Sirdaryo'), ('khorezm', 'Xorazm'), ('karakalpakstan', "Qoraqalpog'iston")], max_length=50, verbose_name='Viloyat')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('inactive', 'Faol emas'), ('blocked', 'Bloklangan')], default='pending', max_length=20, verbose_name='Status')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Jami buyurtmalar')),
                ('completed_orders', models.IntegerField(default=0, verbose_name='Yetkazilgan')),
                ('cancelled_orders', models.IntegerField(default=0, verbose_name='Bekor qilingan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
            ],
            options={
                'verbose_name': 'Kuryer',
                'verbose_name_plural': 'Kuryerlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='courier_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kuryerga berilgan'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.courier'),
        ),
        migrations.CreateModel(
            name='CourierToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Ishlatilgan vaqt')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tokens', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='store.courier')),
            ],
            options={
                'verbose_name': 'Kuryer Tokeni',
                'verbose_name_plural': 'Kuryer Tokenlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
