# Generated by Django 5.2.9 on 2025-12-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_courier_order_courier_assigned_at_order_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan vaqti'),
        ),
    ]
