# Generated by Django 5.2.9 on 2025-12-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_delivered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier_assigned_at',
        ),
        migrations.AddField(
            model_name='order',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivering_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Yo'lga chiqdi"),
        ),
        migrations.AlterField(
            model_name='courier',
            name='region',
            field=models.CharField(choices=[('tashkent', 'Toshkent'), ('samarkand', 'Samarqand'), ('bukhara', 'Buxoro'), ('andijan', 'Andijon'), ('fergana', "Farg'ona"), ('namangan', 'Namangan'), ('kashkadarya', 'Qashqadaryo'), ('surkhandarya', 'Surxondaryo'), ('jizzakh', 'Jizzax'), ('syrdarya', 'Sirdaryo'), ('navoiy', 'Navoiy'), ('khorezm', 'Xorazm'), ('karakalpakstan', "Qoraqalpog'iston")], max_length=50, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.courier', verbose_name='Kuryer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='store.product', verbose_name='Mahsulotlar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('delivering', "Yo'lda"), ('delivered', 'Yetkazilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat'),
        ),
    ]
