# Generated by Django 5.2.9 on 2025-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslider',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Slider', 'verbose_name_plural': 'Sliderlar'},
        ),
        migrations.RemoveField(
            model_name='homeslider',
            name='price',
        ),
        migrations.RemoveField(
            model_name='homeslider',
            name='url',
        ),
        migrations.AddField(
            model_name='homeslider',
            name='button_text',
            field=models.CharField(default='Batafsil', max_length=50, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='button_url',
            field=models.CharField(default='/', max_length=200, verbose_name='Tugma havolasi'),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='slider_type',
            field=models.CharField(choices=[('image', 'Rasm'), ('video', 'Video')], default='image', max_length=10, verbose_name='Slider turi'),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='slider_videos/', verbose_name='Video fayl'),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video URL (YouTube, Vimeo)'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
    ]
