# Generated by Django 5.2.9 on 2025-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homeslider_options_remove_homeslider_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='aboutUsDescription',
            field=models.TextField(verbose_name='Biz haqimizda tavsifi'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='aboutUsImage',
            field=models.ImageField(upload_to='about/us/', verbose_name='Biz haqimizda rasmi'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='aboutUsTitle',
            field=models.CharField(max_length=200, verbose_name='Biz haqimizda sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='aboutusmissons',
            name='missionDescription',
            field=models.TextField(verbose_name='Maqsad tavsifi'),
        ),
        migrations.AlterField(
            model_name='aboutusmissons',
            name='missionIcon',
            field=models.CharField(max_length=100, verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='aboutusmissons',
            name='missionTitle',
            field=models.CharField(max_length=200, verbose_name='Maqsad sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='aboutusquestions',
            name='questionAnswer',
            field=models.TextField(help_text='Javob javobi', verbose_name='Savol javobi'),
        ),
        migrations.AlterField(
            model_name='aboutusquestions',
            name='questionTitle',
            field=models.CharField(help_text='Savol matni', max_length=200, verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='aboutusstats',
            name='statTitle',
            field=models.CharField(max_length=200, verbose_name='Statistika sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='aboutusstats',
            name='statValue',
            field=models.IntegerField(verbose_name='Statistika qiymati'),
        ),
        migrations.AlterField(
            model_name='aboutusteam',
            name='teamFullName',
            field=models.CharField(max_length=100, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='aboutusteam',
            name='teamImage',
            field=models.ImageField(upload_to='about/team/', verbose_name='Jamoa rasmi'),
        ),
        migrations.AlterField(
            model_name='aboutusteam',
            name='teamPosition',
            field=models.CharField(max_length=100, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='aboutusvalues',
            name='valueDescription',
            field=models.TextField(verbose_name='Qadriyat tavsifi'),
        ),
        migrations.AlterField(
            model_name='aboutusvalues',
            name='valueIcon',
            field=models.CharField(max_length=100, verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='aboutusvalues',
            name='valueTitle',
            field=models.CharField(max_length=200, verbose_name='Qadriyat sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='description',
            field=models.TextField(verbose_name='Sayt tavsifi'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(upload_to='site/logo/', verbose_name='Sayt logotipi'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram URL'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sayt nomi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='feedback',
            field=models.TextField(verbose_name='Fikr-mulohaza'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rate',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Reyting (1-5)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hudud'),
        ),
    ]
