# Generated by Django 5.2.9 on 2025-12-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_aboutus_aboutusdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusteam',
            name='teamAbout',
            field=models.TextField(blank=True, help_text='Masalan: 20 yillik tajribaga ega dengiz mahsulotlari mutaxassisi', null=True, verbose_name="Jamoa a'zosi haqida (Ozroq ma'lumot)"),
        ),
    ]
