# Generated by Django 5.2.9 on 2025-12-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutusteam_teamabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusquestions',
            name='questionAnswer',
            field=models.TextField(help_text='Sifatli mahsulotlarni hamyonbop narxlarda taklif qilamiz', verbose_name='Savol javobi'),
        ),
        migrations.AlterField(
            model_name='aboutusquestions',
            name='questionTitle',
            field=models.CharField(help_text='Qulay Narxlar', max_length=200, verbose_name='Savol'),
        ),
    ]
