# Generated by Django 5.2.9 on 2025-12-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_aboutusquestions_questionanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='Youtube URL'),
        ),
    ]
