# Generated by Django 5.2.9 on 2025-12-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sitesetting_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video')], default='image', max_length=10, verbose_name='Media turi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/images/', verbose_name='Rasm')),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery/videos/', verbose_name='Video fayl')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL (YouTube, Vimeo)')),
                ('category', models.CharField(blank=True, help_text='Masalan: Ish jarayonlari, Xabarlar, Mahsulotlar', max_length=100, null=True, verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Galereya',
                'verbose_name_plural': 'Galereya',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
