"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from django.urls import reverse_lazy

load_dotenv()  # Load environment variables from .env file
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '/your-default-secret-key/')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
SIGNAL_HANDLERS = True

ALLOWED_HOSTS = ["lajvar.uz", "www.lajvar.uz", "localhost", "bftgroup.trade", "127.0.0.1"]



CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = False  # Better to explicitly whitelist
CORS_REPLACE_HTTPS_REFERER = True

# Update these lists
CORS_ORIGIN_WHITELIST = [
    "https://www.lajvar.uz",
    "http://www.lajvar.uz",
    "https://bftgroup.trade",
    "http://bftgroup.trade",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://lajvar.uz",
    "http://lajvar.uz",
]

CSRF_TRUSTED_ORIGINS = [
    "https://www.lajvar.uz",
    "http://www.lajvar.uz",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://lajvar.uz",
    "http://lajvar.uz",
    "https://bftgroup.trade",
    "http://bftgroup.trade",
]



# Set CSRF cookie domain (use None for local development)
CSRF_COOKIE_DOMAIN = None  # Or ".ngrok-free.app" if using ngrok in production
CSRF_COOKIE_SECURE = True  # For HTTPS
CSRF_COOKIE_HTTPONLY = False  # JavaScript needs to access it
CSRF_COOKIE_SAMESITE = 'Lax'  # Or 'None' if needed for cross-site
# Celery sozlamalari

# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'storages',  # S3 storage support
    'home',
    'store',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.site_settings',
                'home.context_processors.seo_metadata',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('PGDATABASE', 'railway'),
#         'USER': os.getenv('PGUSER', 'postgres'),
#         'PASSWORD': os.getenv('PGPASSWORD'),
#         'HOST': os.getenv('PGHOST'),
#         'PORT': os.getenv('PGPORT', '43431'),
#     }
# }

import dj_database_url

DATABASES = {
    "default": dj_database_url.parse(os.environ.get("DATABASE_URL"))
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Supabase S3 Storage sozlamalari
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', 'd62e1581f5f0e23fcb6480d1bfe4e6bc')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '997ea6d98525e85f686bbdecb85f9b4dfbd1302eaaf451fe6eb16ee2d4877e8f')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'media')  # Supabase bucket nomi
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', 'https://xikvlxlkhysjfarzonsa.storage.supabase.co/storage/v1/s3')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'ap-northeast-1')

# Path-style URLs uchun (Supabase S3 uchun)
# Path-style: https://xikvlxlkhysjfarzonsa.storage.supabase.co/storage/v1/s3/bucket-name/path/to/file
AWS_S3_ADDRESSING_STYLE = 'path'
# Custom domain'ni o'chirish, path-style ishlatish uchun
AWS_S3_CUSTOM_DOMAIN = None

# Object parametrlari
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
    'ACL': 'public-read',  # Har bir fayl uchun majburiy public-read
}

# Public access
AWS_DEFAULT_ACL = 'public-read'
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = False  # URL'larda signature bo'lmasligi uchun

# Location (media fayllar uchun)
AWS_LOCATION = 'media'

# Static va Media URL'lar
STATIC_URL = '/static/'  # Static fayllar hali ham local
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Path-style URL: https://xikvlxlkhysjfarzonsa.storage.supabase.co/storage/v1/s3/bucket-name/media/
MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/'
MEDIA_ROOT = ''

# Storage backends
DEFAULT_FILE_STORAGE = 'config.storage_backends.RailwayS3Storage'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'  # Static uchun hozircha local

# File Upload Settings - Video yuklash uchun optimallashtirilgan
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100 MB - memory'da saqlash
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Gunicorn timeout sozlamalari (environment variable orqali)
# Production'da: export GUNICORN_TIMEOUT=300
# Yoki Procfile'da: web: gunicorn config.wsgi --timeout 300

UNFOLD = {
    "SITE_TITLE": "LajVar Admin",
    "SITE_HEADER": "LajVar Admin",
    "SITE_SUBHEADER": "Boshqaruvchi bo'lim",
    "SITE_URL": "/",
    "SITE_SYMBOL": "🐟",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,
    "SEARCH": False,
    # ⚠️ Qorong’u rejimni yoqish uchun THEME ni olib tashlaymiz
    # "THEME": "light",  ❌ Bu bo‘lmaydi, olib tashlanadi
    # endi foydalanuvchi dark/light ni o‘zi tanlaydi

    "BORDER_RADIUS": "8px",

    "COLORS": {
        "primary": {
            "50": "240 248 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },

    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Menu",
                "collapsable": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "link": reverse_lazy("admin:index"),
                        "icon": "dashboard",
                    },
                    {
                        "title": "Sayt reklama slayderi",
                        "link": reverse_lazy("admin:home_homeslider_changelist"),
                        "icon": "slideshow",
                    },
                    {
                        "title": "Sayt xizmatlari",
                        "link": reverse_lazy("admin:home_service_changelist"),
                        "icon": "home_repair_service",
                    },
                    {
                        "title": "Sayt fikr-mulohazalari",
                        "link": reverse_lazy("admin:home_testimonial_changelist"),
                        "icon": "speaker_notes",
                    },
                    {
                        "title": "Sayt sozlamalari",
                        "link": reverse_lazy("admin:home_sitesetting_changelist"),
                        "icon": "settings",
                    },
                    {
                        "title": "Biz haqimizda",
                        "link": reverse_lazy("admin:home_aboutus_changelist"),
                        "icon": "info",
                    },
                    {
                        "title": "Maqsadlarimiz",
                        "link": reverse_lazy("admin:home_aboutusmissons_changelist"),
                        "icon": "emoji_flags",
                    },
                    {
                        "title": "Qadriyatlarimiz",
                        "link": reverse_lazy("admin:home_aboutusvalues_changelist"),
                        "icon": "diamond",
                    },
                    {
                        "title": "Bizning jamoa a'zolarimiz",
                        "link": reverse_lazy("admin:home_aboutusteam_changelist"),
                        "icon": "groups",
                    },
                    {
                        "title": "Statiska ma'lumotlarimiz",
                        "link": reverse_lazy("admin:home_aboutusstats_changelist"),
                        "icon": "insert_chart",
                    },
                    {
                        "title": "Mahsulotlar",
                        "link": reverse_lazy("admin:store_product_changelist"),
                        "icon": "restaurant",
                    },
                    {
                        "title": "Kategoriya",
                        "link": reverse_lazy("admin:store_category_changelist"),
                        "icon": "category",
                    },
                    {
                        "title": "Buyurtmalar",
                        "link": reverse_lazy("admin:store_order_changelist"),
                        "icon": "shopping_cart",
                    },
                    {
                        "title": "Savollarga javoblar",
                        "link": reverse_lazy("admin:home_aboutusquestions_changelist"),
                        "icon": "help_center",
                    }
                ],
            }
        ],
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
