"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '/your-default-secret-key/')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
SIGNAL_HANDLERS = True

ALLOWED_HOSTS = ["lajvar.uz", "www.lajvar.uz", "localhost", ]



CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = False  # Better to explicitly whitelist
CORS_REPLACE_HTTPS_REFERER = True

# Update these lists
CORS_ORIGIN_WHITELIST = [
    "https://www.lajvar.uz",
    "http://www.lajvar.uz",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://lajvar.uz",
    "http://lajvar.uz",
]

CSRF_TRUSTED_ORIGINS = [
    "https://www.lajvar.uz",
    "http://www.lajvar.uz",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://lajvar.uz",
    "http://lajvar.uz",
]



# Set CSRF cookie domain (use None for local development)
CSRF_COOKIE_DOMAIN = None  # Or ".ngrok-free.app" if using ngrok in production
CSRF_COOKIE_SECURE = True  # For HTTPS
CSRF_COOKIE_HTTPONLY = False  # JavaScript needs to access it
CSRF_COOKIE_SAMESITE = 'Lax'  # Or 'None' if needed for cross-site
# Celery sozlamalari

# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
   
    'home',
    'store',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('PGDATABASE', 'railway'),
        'USER': os.getenv('PGUSER', 'postgres'),
        'PASSWORD': os.getenv('PGPASSWORD'),
        'HOST': os.getenv('PGHOST'),
        'PORT': os.getenv('PGPORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

UNFOLD = {
    "SITE_TITLE": "Baliq OvqatiUz Admin",
    "SITE_HEADER": "Baliq OvqatiUz Admin",
    "SITE_SUBHEADER": "Boshqaruvchi bo'lim",
    "SITE_URL": "/",
    "SITE_SYMBOL": "🐟",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,
    "SEARCH": False,
    # ⚠️ Qorong’u rejimni yoqish uchun THEME ni olib tashlaymiz
    # "THEME": "light",  ❌ Bu bo‘lmaydi, olib tashlanadi
    # endi foydalanuvchi dark/light ni o‘zi tanlaydi

    "BORDER_RADIUS": "8px",

    "COLORS": {
        "primary": {
            "50": "240 248 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },

    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Menu",
                "collapsable": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "link": reverse_lazy("admin:index"),
                        "icon": "dashboard",
                    },
                    {
                        "title": "Sayt reklama slayderi",
                        "link": reverse_lazy("admin:home_homeslider_changelist"),
                        "icon": "slideshow",
                    },
                    {
                        "title": "Sayt xizmatlari",
                        "link": reverse_lazy("admin:home_service_changelist"),
                        "icon": "home_repair_service",
                    },
                    {
                        "title": "Sayt fikr-mulohazalari",
                        "link": reverse_lazy("admin:home_testimonial_changelist"),
                        "icon": "speaker_notes",
                    },
                    {
                        "title": "Sayt sozlamalari",
                        "link": reverse_lazy("admin:home_sitesetting_changelist"),
                        "icon": "settings",
                    },
                    {
                        "title": "Biz haqimizda",
                        "link": reverse_lazy("admin:home_aboutus_changelist"),
                        "icon": "info",
                    },
                    {
                        "title": "Maqsadlarimiz",
                        "link": reverse_lazy("admin:home_aboutusmissons_changelist"),
                        "icon": "emoji_flags",
                    },
                    {
                        "title": "Qadriyatlarimiz",
                        "link": reverse_lazy("admin:home_aboutusvalues_changelist"),
                        "icon": "diamond",
                    },
                    {
                        "title": "Bizning jamoa a'zolarimiz",
                        "link": reverse_lazy("admin:home_aboutusteam_changelist"),
                        "icon": "groups",
                    },
                    {
                        "title": "Statiska ma'lumotlarimiz",
                        "link": reverse_lazy("admin:home_aboutusstats_changelist"),
                        "icon": "insert_chart",
                    },
                    {
                        "title": "Mahsulotlar",
                        "link": reverse_lazy("admin:store_product_changelist"),
                        "icon": "restaurant",
                    },
                    {
                        "title": "Kategoriya",
                        "link": reverse_lazy("admin:store_category_changelist"),
                        "icon": "category",
                    },
                    {
                        "title": "Buyurtmalar",
                        "link": reverse_lazy("admin:store_order_changelist"),
                        "icon": "shopping_cart",
                    },
                    {
                        "title": "Savollarga javoblar",
                        "link": reverse_lazy("admin:home_aboutusquestions_changelist"),
                        "icon": "help_center",
                    }
                ],
            }
        ],
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
